/**
 * University of Illinois/NCSA
 * Open Source License
 * 
 * Copyright (c) 2008, Board of Trustees-University of Illinois.  
 * All rights reserved.
 * 
 * Developed by: 
 * 
 * Automated Learning Group
 * National Center for Supercomputing Applications
 * http://www.seasr.org
 * 
 *  
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal with the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions: 
 * 
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimers. 
 * 
 *  * Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimers in the 
 *    documentation and/or other materials provided with the distribution. 
 * 
 *  * Neither the names of Automated Learning Group, The National Center for
 *    Supercomputing Applications, or University of Illinois, nor the names of
 *    its contributors may be used to endorse or promote products derived from
 *    this Software without specific prior written permission. 
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
 * CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * WITH THE SOFTWARE.
 */ 
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.11.16 at 02:15:21 PM CST 
//


package org.seasr.meandre.support.components.io.dataproxy;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ncsa.d2k.modules.core.io.proxy package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 * TODO: testing
 * @author D. Searsmith (conversion to SEASR 6/08)
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DataObjectCacheInfo_QNAME = new QName("", "dataObjectCacheInfo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ncsa.d2k.modules.core.io.proxy
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataObjectCacheRecord }
     * 
     */
    public DataObjectCacheRecord createDataObjectCacheRecord() {
        return new DataObjectCacheRecord();
    }

    /**
     * Create an instance of {@link DataObjectCacheRecords }
     * 
     */
    public DataObjectCacheRecords createDataObjectCacheRecords() {
        return new DataObjectCacheRecords();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataObjectCacheRecords }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dataObjectCacheInfo")
    public JAXBElement<DataObjectCacheRecords> createDataObjectCacheInfo(DataObjectCacheRecords value) {
        return new JAXBElement<DataObjectCacheRecords>(_DataObjectCacheInfo_QNAME, DataObjectCacheRecords.class, null, value);
    }

}
