/**
*
* University of Illinois/NCSA
* Open Source License
*
* Copyright (c) 2008, NCSA.  All rights reserved.
*
* Developed by:
* The Automated Learning Group
* University of Illinois at Urbana-Champaign
* http://www.seasr.org
*
* Permission is hereby granted, free of charge, to any person obtaining
* a copy of this software and associated documentation files (the
* "Software"), to deal with the Software without restriction, including
* without limitation the rights to use, copy, modify, merge, publish,
* distribute, sublicense, and/or sell copies of the Software, and to
* permit persons to whom the Software is furnished to do so, subject
* to the following conditions:
*
* Redistributions of source code must retain the above copyright
* notice, this list of conditions and the following disclaimers.
*
* Redistributions in binary form must reproduce the above copyright
* notice, this list of conditions and the following disclaimers in
* the documentation and/or other materials provided with the distribution.
*
* Neither the names of The Automated Learning Group, University of
* Illinois at Urbana-Champaign, nor the names of its contributors may
* be used to endorse or promote products derived from this Software
* without specific prior written permission.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL THE CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE
* FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
* CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
* WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS WITH THE SOFTWARE.
*
*/

package org.seasr.meandre.components.tools.tapor.restservice;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URL;

import org.apache.commons.httpclient.HostConfiguration;
import org.apache.commons.httpclient.HttpClient;
import org.apache.commons.httpclient.SimpleHttpConnectionManager;
import org.apache.commons.httpclient.methods.PostMethod;
import org.meandre.annotations.Component;
import org.meandre.annotations.ComponentInput;
import org.meandre.annotations.ComponentOutput;
import org.meandre.annotations.ComponentProperty;
import org.meandre.annotations.Component.Licenses;
import org.meandre.core.ComponentContext;
import org.meandre.core.ComponentContextProperties;
import org.meandre.core.ComponentExecutionException;
import org.seasr.datatypes.BasicDataTypesTools;
import org.seasr.meandre.components.abstracts.AbstractExecutableComponent;
import org.seasr.meandre.components.tools.Names;
import org.seasr.meandre.support.components.datatype.parsers.DataTypeParser;

@Component(creator="Lily Dong",
           description="Demonstrates how to construct a interface to " +
           "consume rest service of concordance of Tapor at " +
           "http://tada.mcmaster.ca/Main/TAPoRwareHTMLConcordance.",
           name="Concordance",
           tags="concordance rest service",
           rights = Licenses.UofINCSA,
           baseURL="meandre://seasr.org/components/foundry/",
           dependency = {"protobuf-java-2.2.0.jar"}

)

public class Concordance extends AbstractExecutableComponent {

	//------------------------------ INPUTS ------------------------------------------------------

	@ComponentInput(
			name= Names.PORT_TEXT,
			description="Input text to be analyzed." +
			"<br>TYPE: java.lang.String" +
            "<br>TYPE: org.seasr.datatypes.BasicDataTypes.Strings" +
            "<br>TYPE: byte[]" +
            "<br>TYPE: org.seasr.datatypes.BasicDataTypes.Bytes" +
            "<br>TYPE: java.lang.Object"
    )
    public final static String IN_TEXT = Names.PORT_TEXT;

	//------------------------------ OUTPUTS -----------------------------------------------------

	@ComponentOutput(
	        name = Names.PORT_TEXT,
	        description = "Output XML document generated by TAPoR." +
	        "<br>TYPE: org.seasr.datatypes.BasicDataTypes.Strings"
	)
	protected static final String OUT_TEXT = Names.PORT_TEXT;

	//------------------------------ PROPERTIES --------------------------------------------------

	@ComponentProperty(
	        description = "Any valid HTML tag in your submitted HTML text.",
            name = Names.PROP_TAPoR_HTML_TAG,
            defaultValue = "body"
	)
	protected static final String PROP_HTML_TAG = Names.PROP_TAPoR_HTML_TAG;

	@ComponentProperty(
			description = "Unix styled pattern you want to find in the text.",
			name = Names.PROP_TAPoR_PATTERN,
			defaultValue = "*"
	)
	protected static final String PROP_PATTERN = Names.PROP_TAPoR_PATTERN;

	@ComponentProperty(
			description = "Value can be 1,2,3 or 4 which corresponding to " +
			"Words, Lines, Sentences or Paragraphs respectively.",
			name = Names.PROP_TAPoR_CONTEXT,
			defaultValue = "1"
	)
	protected static final String PROP_CONTEXT = Names.PROP_TAPoR_CONTEXT;

	@ComponentProperty(
			description = "Number of words, lines, sentences or paragraphs " +
			"before and after the specified context .",
			name = Names.PROP_TAPoR_CONTEXT_LENGTH,
			defaultValue = "5"
	)
	protected static final String PROP_CONTEXT_LENGTH = Names.PROP_TAPoR_CONTEXT_LENGTH;

	@ComponentProperty(
	        description = "A select control for output format, and could be " +
	        "1(HTML), " +
	        "2(XML), " +
	        "3(Anything), " +
	        "4(Tab).",
            name = Names.PROP_TAPoR_OUT_FORMAT,
            defaultValue = "4"
	)
	protected static final String PROP_OUT_FORMAT = Names.PROP_TAPoR_OUT_FORMAT;

	//--------------------------------------------------------------------------------------------

	private static String serviceLoc = "http://tapor1-dev.mcmaster.ca/~restserv/html/concordance";

	//--------------------------------------------------------------------------------------------

	@Override
    public void initializeCallBack(ComponentContextProperties ccp) throws Exception {
	}

	@Override
	public void executeCallBack(ComponentContext cc) throws Exception {
		String htmlTag = cc.getProperty(PROP_HTML_TAG);
		String pattern = cc.getProperty(PROP_PATTERN);
		String context = cc.getProperty(PROP_CONTEXT);
		String contextLen = cc.getProperty(PROP_CONTEXT_LENGTH);
		String outFormat = cc.getProperty(PROP_OUT_FORMAT);

		String htmlInput = DataTypeParser.parseAsString(
				cc.getDataComponentFromInput(IN_TEXT))[0];

    	try {
    		URL url = new URL(serviceLoc);

    		HostConfiguration hostConfig = new HostConfiguration();
        	hostConfig.setHost(url.getHost(), url.getPort());
        	HttpClient httpClient = new HttpClient(new SimpleHttpConnectionManager());
        	httpClient.setHostConfiguration(hostConfig);
        	PostMethod postMethod = new PostMethod(serviceLoc);

			postMethod.addParameter("htmlInput", htmlInput);
  			postMethod.addParameter("htmlTag", htmlTag);;
			postMethod.addParameter("pattern", pattern);
			postMethod.addParameter("context", context);
			postMethod.addParameter("contextlength", contextLen);
			postMethod.addParameter("outFormat", outFormat);

        	httpClient.executeMethod(postMethod);

        	BufferedReader in = new BufferedReader(
        			new InputStreamReader(postMethod.getResponseBodyAsStream()));
        	String line = null;
        	StringBuffer buf = new StringBuffer();
        	while((line = in.readLine()) != null)
        		buf.append(line).append("\n");

        	in.close();

        	cc.pushDataComponentToOutput(
        			OUT_TEXT,
        			BasicDataTypesTools.stringToStrings(buf.toString()));

    	}catch(Exception e) {
    		throw new ComponentExecutionException(e);
    	}
    }

    @Override
    public void disposeCallBack(ComponentContextProperties ccp) throws Exception {
	}
}
